x-node-version: &node-version node:23.1.0

services:
  db:
    image: postgres:17.0
    container_name: sman_db
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_DB=sman
      - POSTGRES_USER=sman
      - POSTGRES_PASSWORD=smanserverpostgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgsql-sock:/var/run/postgresql
    networks:
      - web

  root:
    image: *node-version
    container_name: sman_root
    working_dir: /app
    volumes:
      - .:/app
    command: bash -c "yarn install"

  backend:
    image: *node-version
    container_name: sman_nestjs
    working_dir: /app
    ports:
      - "9000:9000"
    networks:
      - web
    depends_on:
      - db
      - root
    volumes:
      - pgsql-sock:/var/run/postgresql
      - .:/app
      - ./packages/backend/assets:/var/lib/images
    command: bash -c "yarn backend:dev"

  frontend:
    image: *node-version
    container_name: sman_nextjs
    working_dir: /app
    ports:
      - "3000:3000"
    networks:
      - web
    depends_on:
      - root
      - backend
    volumes:
      - .:/app
    command: bash -c "yarn frontend:dev"


volumes:
  pgdata:
  pgsql-sock:

networks:
  web:
