export const GLOBAL_PREFIXES = {
  AUTH: 'auth',
  ROLE: 'role',
  USER: 'user',
  CATEGORY: 'category',
  SUB_CATEGORY: 'sub-category',
  PRODUCT: 'product',
  PROMOTION: 'promotion',
  PROMOTION_BANNER: 'promotion-banner',
  INGREDIENT: 'ingredient',
  POINT_OF_SALE: 'point-of-sale',
  DISTRICT: 'district',
  ORDER: 'order',
} as const;

export const ENDPOINTS = {
  DEFAULT: {
    ALL: '',
    CREATE: '',
    BY_ID: ':id',
    UPDATE: ':id',
    REMOVE: ':id',
  },
  AUTH: {
    LOGIN: 'login',
    REGISTER: 'register',
    REFRESH: 'refresh',
    IS_AUTH: 'is-auth',
    LOGOUT: 'logout',
  },
  USER: {
    CREATE: '',
    ALL: 'all',
    INFO: 'info',
    BY_ID: ':id',
    UPDATE_SELF: '',
    UPDATE: ':id',
    REMOVE: ':id',
    ADDRESS: 'address',
    ACTIVE_ADDRESS: 'address/active',
    UPDATE_ADDRESS: 'address/:id',
    REMOVE_ADDRESS: 'address/:id',
    ADD_ROLES: 'roles/:id',
    REMOVE_ROLE: 'roles/:id',
  },
  PRODUCT: {
    ALL: '',
    CREATE: '',
    ADD_PHOTOS: 'photos/:id',
    ADD_INGREDIENTS: 'ingredients/:id',
    BY_ID: ':id',
    UPDATE: ':id',
    REMOVE: ':id',
    REMOVE_PHOTO: 'photos/:id',
  },
  PROMOTION: {
    ALL: '',
    CREATE: '',
    BY_ID: ':id',
    UPDATE: ':id',
    REMOVE: ':id',
    ADD_PHOTOS: 'photos/:id',
    REMOVE_PHOTO: 'photos/:id',
    ADD_PRODUCTS: 'products/:id',
  },
  PROMOTION_BANNER: {
    ALL: '',
    CREATE: '',
    UPDATE: ':id',
    REMOVE: ':id',
  },
} as const;
